// types here
export const POST_LOGIN = "POST_LOGIN";

export const POST_REGISTER = "POST_REGISTER";

export const GET_PRODUCT = "GET_PRODUCT";

// PRODUCT
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const POST_PRODUCT_SEARCH = "POST_PRODUCT_SEARCH";

// Category
export const GET_PRODUCT_BY_ALL_CATEGORY = "GET_PRODUCT_BY_ALL_CATEGORY";

// Profile
export const GET_PROFILE = "GET_PROFILE";
export const POST_UPDATE_PROFILE = "POST_UPDATE_PROFILE";

// Offering Product
export const POST_PRODUCT_OFFERING_NEGOTATION = "POST_PRODUCT_OFFERING";

// Aceept Negotation

export const PUT_PRODUCT_ACCEPT_NEGOTATION = "PUT_PRODUCT_ACCEPT_NEGOTATION";

// Notification
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_DETAIL_NOTIFICATION = "GET_DETAIL_NOTIFICATION";

// Seller
export const POST_PRODUCT_SELLER = "POST_PRODUCT_SELLER";
export const GET_MY_PRODUCT = "GET_MY_PRODUCT";

export const CHANGE_STATUS_PRODUCT = "CHANGE_STATUS_PRODUCT";

// Wishlist
export const GET_WISHLIST = "GET_WISHLIST";
export const POST_WISHLIST = "POST_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
