// data city of indonesia

const dataCity = [
    "Kota Banda Aceh",
    "Kota Sabang",
    "Kota Subulussalam",
    "Kota Medan",
    "Kota Tanjung Balai",
    "Kota Binjai",
    "Kota Tebing Tinggi",
    "Kota Padang Sidempuan",
    "Kota Padang",
    "Kota Padang Panjang",
    "Kota Bukittinggi",
    "Kota Pekan Baru",
    "Kota Dumai",
    "Kota Jambi",
    "Kota Sungai Penuh",
    "Kota Palembang",
    "Kota Bengkulu",
    "Kota Bandar Lampung",
    "Kota Metro",
    "Kota Pangkal Pinang",
    "Kota Batam",
    "Kota Tanjung Pinang",
    "Kota Jakarta Timur",
    "Kota Jakarta Selatan",
    "Kota Jakarta Barat",
    "Kota Jakarta Utara",
    "Kota Jakarta Pusat",
    "Kota Bandung",
    "Kota Banjar",
    "Kota Tasikmalaya",
    "Kota Cimahi",
    "Kota Depok",
    "Kota Bekasi",
    "Kota Cirebon",
    "Kota Sukabumi",
    "Kota Bogor",
    "Kota Semarang",
    "Kota Tegal",
    "Kota Pekalongan",
    "Kota Salatiga",
    "Kota Surakarta",
    "Kota Magelang",
    "Kota Yogyakarta",
    "Kota Surabaya",
    "Kota Batu",
    "Kota Madiun",
    "Kota Mojokerto",
    "Kota Pasuruan",
    "Kota Probolinggo",
    "Kota Malang",
    "Kota Blitar",
    "Kota Kediri",
  ];

export default dataCity;
